site_name: BBG-Wiki

theme:
  name: material
  palette:
    primary: orange
  logo: assets/images/bbglabLOGO_small.png
  favicon: assets/images/bbglabLOGO_small.png
markdown_extensions:
  - admonition
extra_css:
  - stylesheets/extra.css
