site_name: BBG-Wiki

theme:
  name: material
  palette:
    primary: orange
  logo: assets/images/bbglabLOGO_small.png
  favicon: assets/images/bbglabLOGO_small.png
## === Uncomment for extra color options ===
# extra_css:
#   - stylesheets/extra.css
