site_name: BBG-Wiki

theme:
  name: material
  palette:
    primary: orange
    accent: orange
  logo: assets/images/bbglabLOGO_small.png
  favicon: assets/images/bbglabLOGO_small.png
  features:
    - navigation.top

markdown_extensions:
  - admonition
  - toc:
      permalink: True
  - attr_list
extra_css:
  - stylesheets/extra.css
