site_name: BBG-Wiki

theme:
  name: material
  palette:
    primary: orange
  logo: assets/images/bbglabLOGO_small.png
  favicon: assets/images/bbglabLOGO_small.png
markdown_extensions:
  - admonition
  - toc:
      permalink: True
  # - markdown_include.include:
  #     base_path: docs
  - attr_list
extra_css:
  - stylesheets/extra.css
